Layout fixes
p-szalast/Candy-Street pull request #8
Opened 2023-01-24 15:48 UTC by p-szalast

2023-01-24 19:17 UTC, cyborgx99 requested changes

2023-01-24 19:17 UTC, cyborgx99 commented on src/common/styles/componentsStyles.ts
> +import * as theme from "./theme";
Remind me tomorrow to show you how to use Themes in Styled Components :)

2023-01-24 19:17 UTC, cyborgx99 commented on src/common/styles/componentsStyles.ts
> +  background: #fff;
This can also come from theme

2023-01-24 19:17 UTC, cyborgx99 commented on src/common/styles/componentsStyles.ts
> +  border: 0px solid #fff;
does it even do anything if it's 0px?

2023-01-24 19:17 UTC, cyborgx99 commented on src/components/OrderHistory/OrderHistoryListStyles.ts
> +  justify-content: start;
I'm not sure "start" does anything here. It should be at least flex-start if it's a flex container. And it's the default value anyway

2023-01-24 19:17 UTC, cyborgx99 commented on src/components/Summary/SummaryStyles.ts
> +  display: block;
div is block by default. No reason to indicate that

2023-01-25 09:40 UTC, p-szalast commented on src/components/OrderHistory/OrderHistoryListStyles.ts
> +  justify-content: start;
Here it extends custom component: Container and in Container justify-contnet is set to center by default

2023-01-25 10:44 UTC, cyborgx99 approved these changes

2023-01-25 18:23 UTC, merged